spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  default-license-name: kinglin
  default-assignee-name: kingli
  default-expiry-date: 2999-12-12